spring:
  h2:
    datasource:
      url: jdbc:h2:mem:testdb
      username: sa
      password:
      driverClassName: org.h2.Driver
    console:
      enabled: true
      path: /h2-ui
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update